name: chili_labs_task
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.6
  equatable: ^2.0.5
  flutter_dotenv: ^5.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  http: ^1.2.0

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - .env